import { Roboto } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider";
import { PlayerProvider } from "@/contexts/PlayerContext";
import AudioPlayer from "@/components/Tracks/AudioPlayer";
import { Bounce, ToastContainer } from "react-toastify";

const Roboto_Font = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "RockMix FM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Roboto_Font.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
          <PlayerProvider>
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)"
                }
              }
            >
              <AppSidebar variant="inset" />
              <SidebarInset>
                <SiteHeader />
                <main className="flex flex-col lg:flex-row lg:justify-between lg:items-baseline">
                  <div className="flex flex-1 flex-col">
                    <div className="@container/main flex flex-1 flex-col gap-2">
                      <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6 px-4 lg:px-8 relative">
                        {children}
                      </div>
                    </div>
                  </div>
                  <div className="min-w-[300px] border-1 border-emerald-100 dark:border-emerald-800 p-4 m-3">
                  </div>
                </main>
              </SidebarInset>
              <AudioPlayer />
            </SidebarProvider>
          </PlayerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
